name: FitbitSync
options:
  bundleIdPrefix: com.fitbitsync
  deploymentTarget:
    iOS: "17.0"

settings:
  SWIFT_VERSION: "5.9"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  FitbitSync:
    type: application
    platform: iOS
    sources:
      - FitbitSync
    entitlements:
      path: FitbitSync/FitbitSync.entitlements
    info:
      path: FitbitSync/Info.plist
      properties:
        CFBundleDisplayName: FitbitSync
        CFBundleIdentifier: com.fitbitsync.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.fitbitsync.auth
            CFBundleURLSchemes:
              - fitbitsync
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.fitbitsync.app
      INFOPLIST_FILE: FitbitSync/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
